# Generated by Django 5.2.7 on 2025-10-22 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start date and time for the quiz'),
            preserve_default=False,
        ),
    ]
