# Generated by Django 5.2.7 on 2025-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
