# Generated by Django 5.2.7 on 2025-10-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_customuser_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.class'),
            preserve_default=False,
        ),
    ]
