# Generated by Django 6.0 on 2025-12-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectteacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectteacher',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachersubjectclass',
            name='subject_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachersubjectclass',
            name='classname',
        ),
    ]
