# Generated by Django 5.2.7 on 2025-10-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_subject_subject_class_subjectclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.class'),
            preserve_default=False,
        ),
    ]
