# Generated by Django 6.0 on 2025-12-24 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_subjectteacher_subject_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='teacher_subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teachersubjectclass'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.attempt'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='multiple_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.multiplechoice'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz'),
        ),
        migrations.DeleteModel(
            name='SubjectTeacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='TeacherSubjectClass',
        ),
    ]
