# Generated by Django 5.2.7 on 2025-10-20 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_student_class_enrolled_alter_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Due date for the quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
