# Generated by Django 6.0 on 2026-02-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_teacher_subject_class_alter_attempt_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='randomized_choices_order',
            field=models.JSONField(blank=True, default=dict, help_text='Stores the randomized order of choices for each question'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='randomized_questions_order',
            field=models.JSONField(blank=True, default=list, help_text='Stores the randomized order of question IDs'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], db_index=True, default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(db_index=True, help_text='Due date for the quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(db_index=True, help_text='Start date and time for the quiz'),
        ),
    ]
