# Generated by Django 5.2.7 on 2025-10-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_end_time_remove_quiz_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.student')),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subjectclass')),
            ],
        ),
    ]
