# Generated by Django 5.2.7 on 2025-10-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_studentsubject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubject',
            old_name='subject_class',
            new_name='class_subject',
        ),
    ]
