# Generated by Django 5.2.7 on 2025-10-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_subject_class_studentsubject_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.teacher'),
            preserve_default=False,
        ),
    ]
